### ISSUE TITLE
Mobile: Untranslated "You're sending to" box

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#660] opened 2018-11-29 04:14 UTC
Untranslated 3 phrases on the box from the screenshot. 

**The same box on DESKTOP is translated properly!**

Trinity Version:
0.5.1 (28) Android

![screenshot_20181129-050638_trinity](https://user-images.githubusercontent.com/35224101/49198905-b0ff5400-f395-11e8-9451-442e65e4447a.jpg)

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment] 2018-11-29 06:17
Closing as duplicate of #519

**Closed as completed by rajivshah3** 2018-11-29 06:17 UTC
Labels: Duplicate
