### ISSUE TITLE
Incorrect quorum size shown in node settings

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1878] opened 2019-06-27 19:34 UTC
### Bug description
When quorum gets disabled and enabled again the quorum size got reset to 3 but when I tap on it to change the size it automatically selects 2 and I need to change to 3 and back to 2 to change it.

### Environment Specs
- OS version: iOS 12.1.1
- Trinity version: 0.7.3 (78)

### Steps To Reproduce
1. disable quorum
2. enable it again
3. press to select another `quorum size`

### Expected behaviour
It should show the selected size selected which got reset to 3 after enabling quorum again.

### Actual behaviour
It shows 2 as selected size and just pressing `Done` doesn't change quorum size to 2.
![IMG_E5007](https://user-images.githubusercontent.com/21984138/60295166-55914680-9923-11e9-90ac-5921619617f4.JPG)
![IMG_E5008](https://user-images.githubusercontent.com/21984138/60295169-56c27380-9923-11e9-9072-e0889f5d468c.JPG)

**Comment by rajivshah3** [comment] 2019-07-01 20:32
@laumair I was able to reproduce this on an iOS simulator, but I'm not sure what's causing the problem. It seems to be an inconsistency between the picker and the quorum settings.  

To reproduce:

1. Change quorum size to 2
2. Disable quorum
3. Enable quorum -- quorum size should now say `3`
4. Tap `Quorum size` -- the picker will select `2`

**Comment by cvarley100** [comment] 2019-09-02 14:54
Fixed in 1.1.0

**Closed as completed by cvarley100** 2019-09-02 14:54 UTC
Labels: T - Bug, C - Mobile, L - Need to reproduce
