### ISSUE TITLE
Can't login when node auto-switching disabled

### ISSUE THREAD

**Issue by Hissi88** [iotaledger/trinity-wallet#1914] opened 2019-07-03 18:30 UTC
### Bug description
After disabling **Primary node autoswitching** and selecting a node in the list (no matter which node), I can't login into Trinity anymore nor can I open the settings (it's blank).

When trying to login, this error shows up:
![grafik](https://user-images.githubusercontent.com/45494848/60616079-fa52ce80-9dd0-11e9-9f04-538c87d89dd9.png)

It's reproducable on a fresh installation.

This is in the logs: 
Request Error: Request timed out.

### Environment Specs
What device are you running Trinity on?

- OS version: Windows 7

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: trinity-desktop-win7-1.0.0

### Steps To Reproduce
1. Fresh installation of Trinity
2. Disable node autoswtiching and logout
3.

**Comment by jojoCoWorker** [comment] 2019-07-03 19:38
Same pb on WIN7 too. I thought it was because I added custom nodes, but I think I also disabled Primary node autoswitching. It happens to me at each Trinity update for the last 2 updates.
I'd add that only the node setting page is "blanck", other setting pages are fine on my hand.

**Comment by jojoCoWorker** [comment] 2019-07-03 20:17
I could reproduce with only disabling "Automatic node management" and "Primary node autoswitching" :
![image](https://user-images.githubusercontent.com/33653820/60622277-32154280-9de0-11e9-9f89-ac2808e0f7a9.png)
Then close Trinity, then reopen

**Comment by rihardsgravis** [comment] 2019-07-05 10:38
Fixed in #1914

**Closed as completed by rihardsgravis** 2019-07-05 10:38 UTC
Labels: T - Bug, C - Desktop, L - Has PR
