### ISSUE TITLE
When switching to detailed balances also switch history

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#475] opened 2018-10-05 17:00 UTC
### Description
In the main window when clicking on the balance the balance changes to decimals ( for example from 1.4 GI to 1.4234534 GI ). The balances in the history do not switch and stay at 1.1 GI. Those balances should also be changed to 1.121134 GI

### Environment Specs
Trinity Desktop and Mobile

### Motivation
its less confusing for the user and the current situation seems like a bug

### Am I planning to do it myself with a PR?
no

**Comment by rajivshah3** [comment] 2018-10-05 18:39
Duplicate of #314

**Closed as completed by rajivshah3** 2018-10-05 18:39 UTC
