### ISSUE TITLE
Make it as clear as possible that users must note down their Ledger account index

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#1544] opened 2019-05-16 23:14 UTC
### Description
During Ledger setup, users are warned to note down their Ledger account index.
We should make it as clear as possible that users must note down the index and store it safely. 

### Motivation
There have been several cases of users forgetting this index.

### Am I planning to do it myself with a PR?
Yes.

**Comment by UmbahaSpodPaha** [comment] 2019-05-17 01:12
My idea for this is to completely hide Index number config under Advanced options during setup. Not showing this option to users everytime.

And Advanced options would be small font with not clearly visible text.

**Comment by rajivshah3** [comment] 2019-05-17 11:36
Duplicate of https://github.com/iotaledger/trinity-wallet/issues/1159 :trollface:

**Comment by rajivshah3** [comment] 2019-05-17 19:39
Fixed in #1550

**Closed as completed by rajivshah3** 2019-05-17 19:39 UTC
