### ISSUE TITLE
Cannot login to Trinity

### ISSUE THREAD

**Issue by steffenroeber** [iotaledger/trinity-wallet#832] opened 2018-12-19 22:01 UTC
I always get a 'Cannot fetching account information..." error if I try to login with password.

### Expected behaviour
Login with password works

### Actual behaviour
I get an error message and cannot login

I'm using V
![unbenannt](https://user-images.githubusercontent.com/46009216/50250717-f1288400-03e1-11e9-9f78-5078e6281a9a.PNG)
0.4.5

**Comment by steffenroeber** [comment] 2018-12-19 22:03
Correct Screenshot:
![trinity](https://user-images.githubusercontent.com/46009216/50250807-3351c580-03e2-11e9-9cdc-1d84b084eeb7.PNG)

I tried some different nodes, but none works.

**Comment by rajivshah3** [comment] 2018-12-20 02:09
Hi, what OS are you running and what is the manufacturer and model of your computer?

**Comment by steffenroeber** [comment] 2018-12-20 05:42
Hi, OS  is Windows 10 homeMy pc is an amd x4 phenom

Gesendet von Yahoo Mail auf Android 
 
  Am Do., Dez. 20, 2018 at 3:09 schrieb Rajiv Shah<notifications@github.com>:   Hi, what OS are you running and what is the manufacturer and model of your computer?

**Comment by rajivshah3** [comment] 2018-12-25 06:39
Possibly related to #838 . Are you using a Ledger? @steffenroeber

**Comment by steffenroeber** [comment] 2018-12-25 07:41
Yes, i do.

Gesendet von Yahoo Mail auf Android 
 
  Am Di., Dez. 25, 2018 at 7:39 schrieb Rajiv Shah<notifications@github.com>:   
Possibly related to #838 . Are you using a Ledger? @steffenroeber

**Comment by rajivshah3** [comment] 2018-12-25 07:54
Is anything showing up in the error log?

**Comment by rajivshah3** [comment] 2018-12-25 07:55
Most likely a duplicate of #838

**Closed as completed by rajivshah3** 2018-12-25 07:55 UTC
Labels: C - Desktop, L - Need more information
