### ISSUE TITLE
Currency keeps resetting back to $ 

### ISSUE THREAD

**Issue by eugenekoen** [iotaledger/trinity-wallet#2614] opened 2020-03-04 06:41 UTC
The issue tracker is only for reporting bugs. If you need technical assistance with the Trinity wallet, please consult the [documentation](https://docs.iota.works/trinity). For further assistance, please visit the #help channel on [Discord](https://discord.iota.org).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.iota.org).

### Bug description
Every time i open Trinity Wallet, the currency resets to $ (Dollar). I used to save it to my local currency (ZAR) and when I restart the Wallet, it is back on $. 

### Environment Specs
What device are you running Trinity on?

- Trinty Desktop and Trinity Android. Both do the same. 
- Desktop Version (1.4.3) 
- Android Version (updated through google play store to latest update)

### Expected behaviour
It is supposed to stay on my local currency.

### Actual behaviour
Currency resets to Dollar ($)

**Comment by cvarley100** [comment] 2020-03-05 19:19
Duplicate of #2529

**Closed as completed by cvarley100** 2020-03-05 19:19 UTC
Labels: T - Bug
