### ISSUE TITLE
Desktop wallet locks and refuses to unlock. No clear way to reset the wallet.

### ISSUE THREAD

**Issue by leucinedreams** [iotaledger/trinity-wallet#347] opened 2018-09-08 22:48 UTC
The issue tracker is only for reporting bugs or asking for feature requests.
If you need technical assistance for using Trinity Wallet, please consult the Trinity [documentation](https://docs.iota.works/trinity) and [knowledge base](https://iotaledger.atlassian.net/wiki/spaces/trinity/overview). For further assistance, please visit the #help channel on [Discord](https://discord.gg/7Gu2mG5).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
A general description of the bug.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model: 
- OS version: Linux

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: Desktop 0.3.3

### Steps To Reproduce
1. imported wallet seed
2. set password
3. allow the application to lock such that it requests a password.

### Expected behaviour
unlock application with password

### Actual behaviour
password no longer accepted after locking. 

### Errors
"This password was not recognised. Please try again."

### Description
The ability to easily reset the desktop wallet.

### Motivation
Deleting the appImage doesn't reset the wallet, and I am still locked out. 

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment] 2018-09-09 14:52
@leucinedreams you can reset the wallet by deleting the folder for your OS:
- Windows : `%APPDATA%/Trinity`
 - Linux: `~/.config/Trinity`
 - macOS: `~/Library/Application Support/Trinity`

You're right, though, this should be documented somewhere

**Comment by delki8** [comment] 2018-09-15 00:18
@leucinedreams I was unable to reproduce the problem following the given steps. In my Ubuntu 16.04 the password was accepted correctly after the client is idle for a few minutes and start asking for the password.

**Comment by rajivshah3** [comment] 2018-09-15 00:41
@leucinedreams I'm also unable to reproduce the issue on macOS 10.14

**Comment by rihardsgravis** [comment] 2018-09-18 21:15
Cannot reproduce on macOS or on Ubuntu. Will close this until no new occurrences.

**Comment by rajivshah3** [comment] 2018-09-21 12:24
@rihardsgravis I left this open because of this part: `No clear way to reset the wallet`

**Comment by rajivshah3** [comment] 2018-09-29 18:44
@leucinedreams I wonder if #435 will fix your issue

**Closed as completed** 2018-10-23 02:49 UTC
Labels: Good first issue, C - Desktop, E - Documentation
