### ISSUE TITLE
Mobile: All sending steps untranslated

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#661] opened 2018-11-29 04:18 UTC
All sending steps are untranslated on mobile version **but on desktop these are translated properly!**

So the translations are done but Trinity mobile don't want to use these somehow.

Trinity Version:
0.5.1 (28) Android

![screenshot_20181129-050651_trinity](https://user-images.githubusercontent.com/35224101/49198994-210dda00-f396-11e8-9d78-a124a245c1c8.jpg)
![screenshot_20181129-050705_trinity](https://user-images.githubusercontent.com/35224101/49198995-210dda00-f396-11e8-956c-0e4fd04e61cd.jpg)

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment] 2018-11-29 06:22
Duplicate of #519

**Closed as completed by rajivshah3** 2018-11-29 06:22 UTC
Labels: Duplicate
