### ISSUE TITLE
Trinity Desktop Wallet - Password with special character Issue

### ISSUE THREAD

**Issue by theshock9** [iotaledger/trinity-wallet#381] opened 2018-09-17 13:03 UTC
### Bug description
If you install the Trinity-Desktop-Wallet and start it up you have to type in your Password (Here everything went fine)

Then i Start the Wallet and type in the PWD I got an error for "Bad Password"
I got a PWD that starts with this special Character (circumflex)

`^`

So i type ^1XXXXXXXXXXX but it only gives me 1XXXXXXXXXXX
This special character (circumflex) is not accepted
If you delete the input field and try it again than it works

### Environment Specs
What device are you running Trinity on?

- Model: Intel-PC
- OS version: Windows 10 Pro

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.3

### Steps To Reproduce
See Bug description

### Expected behaviour
special character (circumflex) accepted at first time

### Actual behaviour
special character (circumflex) is not accepted at first time

**Comment by rihardsgravis** [comment] 2018-09-18 21:13
Cannot reproduce on macOS or on Ubuntu.
@theshock9 can you reproduce this once more? When you type the first character `^`. Is it not showing up in the password field at all (masked or unmasked) or is it disappearing at some time entering other characters?

**Comment by theshock9** [comment] 2018-09-19 13:49
I can.
If i close the Wallet and reopen it i got the same result!

If I type "^1" it only shows "1" (unmasked)
Normally you have to type two letters to see the input by this special character!
I got Ubuntu too. If i type "^" in the console it shows nothing until i type the second letter "1" = "^1"

**Comment by rihardsgravis** [comment] 2018-09-19 13:52
@theshock9 Do you have a English or a different keyboard layout? And what key combination do you use to write that character?

**Comment by theshock9** [comment] 2018-09-19 13:57
I got the German keyboard layout!

There is no Key combo. I just have to press this buttuns
^ is on the left side of the number 1


https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg

**Comment by rajivshah3** [comment] 2018-09-21 12:50
Hi @theshock9 , are you still able to reproduce this issue? I asked someone else with the German keyboard layout on Windows and they said that it worked fine for them. Keep in mind that in order to type the `ˆ` character you may need to type `circumflex`+`space` as `circumflex`is a dead key

**Comment by theshock9** [comment] 2018-09-21 13:20
I still can reproduce this issue.

I ask also some guys in the Forum but they say it works for them.
I try it on my Desktop-PC and my LapTop (Bouth on Windwos 10 Pro). Same Problem!

If I type circumflex+space it only shows me the Whitespace. Strange

**Comment by theshock9** [comment] 2018-09-21 13:29
I can type it everywhere. I got 4 Linuxserver. It works everywhere. But not in the Trinity Wallet

And now the other guys tell me it dont work also. He just log out and try it. But if you restart the wallet (Close the Programm and Open it again) it dont work. 4 guys testing. It just shows the 1 and not the ^1

**Comment by rajivshah3** [comment] 2018-09-21 13:36
> If you install the Trinity-Desktop-Wallet and start it up you have to type in your Password (Here everything went fine)
Then i Start the Wallet and type in the PWD I got an error for "Bad Password"

Is this part (it works in one text field but not in the other) still reproducible? If it doesn't work in all fields, I wonder if it might be an electron bug (possibly https://github.com/electron/electron/issues/12128)

**Comment by theshock9** [comment] 2018-09-21 13:52
If I first Type some letter then it works
Let’s say I type 1^1 then it shows 1^1

We test some thigs. If you Install the wallet and fire it up. It first ask you for the Seed. You type it in and the next step is the PWD thing. There I can type ^1 with no Problem because in trinity I type before something for the Seed. First PWD and Seccond PWD Field without Problems.
Close the Wallet and start it again (type in ^1). Nope, don’t work. Delete the input and type in again and it Works!

**Comment by rajivshah3** [comment] 2018-09-21 15:10
Thanks for that information, I think I understand it a bit better now. That's really weird, I'll look into it

**Comment by rihardsgravis** [comment] 2019-04-16 13:17
Reproduction steps (on macOS):
1. Add a German keyboard layout (Settings->Keyboard->Input sources)
2. In a password field (e.g. on Login) try to write `^` (it's `士` key to the left from `1` key)

For German layout the key acts as a dead key and seems like there is a bug in Electron password field (text fields are fine), where dead keys are not registered.

**Comment by cvarley100** [comment] 2019-07-05 14:41
As this is an Electron bug I will close this issue. We can revisit it should Electron fix it.

**Closed as completed by cvarley100** 2019-07-05 14:41 UTC
Labels: T - Bug, C - Desktop
