### ISSUE TITLE
Show time in system timezone

### ISSUE THREAD

**Issue by wonkytonky** [iotaledger/trinity-wallet#270] opened 2018-08-25 19:02 UTC
The issue tracker is only for reporting bugs or asking for feature requests.
If you need technical assistance for using Trinity Wallet, please consult the Trinity [documentation](https://docs.iota.works/trinity) and [knowledge base](https://iotaledger.atlassian.net/wiki/spaces/trinity/overview). For further assistance, please visit the #help channel on [Discord](https://discord.gg/7Gu2mG5).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
when creating transactions they seem to have a difference time as my pc time

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model: 
- OS version: win 10 & latest ubuntu

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 
0.3.2
### Steps To Reproduce
1.make transactions (whatever)
2. look at your system time and the time of transcation 
3. 

### Expected behaviour
time should be same as system time

### Actual behaviour
time of tx is different with system time

### Errors

![image](https://user-images.githubusercontent.com/19390834/44621654-fd745880-a8a9-11e8-9d02-97e1fa45b420.png)

**Comment by rajivshah3** [comment] 2018-08-25 19:08
Hi @wonkytonky ,
This is intended. At this time (pun not intended), we show the transaction time in UTC. In a future update, we'll show the time in the same timezone as the system.

**Comment by wonkytonky** [comment] 2018-08-25 19:15
cool, keep up the good work

**Comment by cvarley100** [comment] 2018-09-12 10:18
Duplicate of https://github.com/iotaledger/trinity-wallet/issues/338

**Closed** 2018-09-12 10:18 UTC
Labels: C - Shared, E - UI/UX, P4 - Low, enhancement

**Comment by rajivshah3** [comment] 2018-10-01 13:21
Resolved in #434
