### ISSUE TITLE
iOS Keyboard does not disappear after auto-filling from 1Password

### ISSUE THREAD

**Issue by john-zaprite** [iotaledger/trinity-wallet#633] opened 2018-11-23 04:41 UTC
### Bug description
The keyboard does not disappear after using iOS 'Passwords' feature to auto-fill a password from 1Password.

### Environment Specs
- iPhone XS
- Trinity version: v 0.5.1 (28)

### Steps To Reproduce
1. Use 1Password to auto-fill a password when logging in
2. iOS keyboard does not disappear, so the Login button cannot be seen
3. 'Done' button on keyboard is greyed out, so you cannot login/proceed (workaround: type a space and then backspace to activate the 'Done'  #button)

### Expected behaviour
iOS keyboard should slide back down after auto-fill is used. Or, 'Done' button should activate.

### Actual behaviour
Keyboard stays visible and there is no way to login/proceed.

![trinity-ios-keyboard-issue](https://user-images.githubusercontent.com/12265052/48928658-1d5ded00-ee96-11e8-9c09-f9f09e803ea2.jpg)

**Comment by rajivshah3** [comment] 2018-11-24 19:31
Hi @john-magill ,
Nice catch, I'm surprised I never noticed this before. This is actually an issue with the iOS SDK (I was able to reproduce this in native iOS apps such as 1Password). I'll submit a report to Apple and keep this thread updated with any progress made on that side. Thanks for reporting this!

**Comment by john-zaprite** [comment] 2018-11-24 21:22
Yes I see it's the same with keychain passwords too. It doesn't auto-submit the form. Interesting!

**Comment by rajivshah3** [comment] 2018-11-24 22:33
Submitted to Apple: [rdar://46229116](https://openradar.appspot.com/radar?id=6158871106158592)

**Comment by rajivshah3** [comment] 2018-11-28 19:28
@john-magill I'll close this for now since it's not a Trinity bug, but I'll keep this thread updated with any replies I get from Apple

**Closed as completed by rajivshah3** 2018-11-28 19:28 UTC
Labels: P - iOS, C - Mobile, L - Assigned, L - Waiting for Upstream
