### ISSUE TITLE
Checksum different on printout when compared to adding seed for first time

### ISSUE THREAD

**Issue by Oldmate099** [iotaledger/trinity-wallet#1269] opened 2019-04-07 12:39 UTC
I have created over 53 accounts using the following process

Create new seed,
Change letters / numbers
Print seed
I print to PDF and have it on the screen to type back in
I type the seed in for the first time and the seed loads.

Problem / Issue:
On Occasion (approx 5 times out of 52) the checksum on the printed version (PDF) on screen is different to the checksum shown on the screen when completing the entering of the seed.
The seed is correct and loads as per usual. so has no effect on the seed itself.

I had entered the seed incorrectly and get the expected error, so i would expect it is something wrong in the checksum creation

**Comment by rajivshah3** [comment] 2019-04-07 16:36
Hi @Oldmate099 please fill out the template. It gives us important information necessary to investigate the issue such as Trinity version and OS.

**Comment by rajivshah3** [comment] 2019-05-13 15:12
@Oldmate099 could you confirm whether this is still occurring in the latest version? We also need you to fill out the template

**Comment by cvarley100** [comment] 2019-07-08 14:52
@Oldmate099 Any updates?

**Comment by cvarley100** [comment] 2019-08-27 08:40
Closing due to age and inability to reproduce.

**Closed as completed** 2019-08-27 08:39 UTC
Labels: T - Bug, C - Desktop, L - Need more information, P1 - Critical
