### ISSUE TITLE
Can't get passed the "choose your ledger account index"

### ISSUE THREAD

**Issue by t0rv1c** [iotaledger/trinity-wallet#589] opened 2018-11-08 11:15 UTC
### Bug description
Can't get passed the "choose your ledger account index". Clicking continue does nothing.
Ledger is definitely recognized as soon as I plug it in and enter the pass code.
Ledger works with Ledger Live although I need to sudo to get to interact with the Ledger wallet. Trying  to run Trinity with sudo doesn't work: it lets me know I need to install dependencies that are already installed....
How to get a log???

### Environment Specs
- Manufacturer: Google
- Model: Pixelbook
- OS version: Ubuntu 18.04
- Trinity version: 0.4.1

**Comment by cvarley100** [comment] 2018-11-21 18:27
@t0rv1c Have you tried again with the latest release? (0.4.2)

**Comment by t0rv1c** [comment] 2018-11-21 23:18
@cvarley100 yes, not working

**Comment by t0rv1c** [comment] 2018-11-21 23:19
@rajivshah3 how do I get a log?

**Comment by rajivshah3** [comment] 2018-11-22 00:17
Since I don't know where this issue is coming from, it's hard to tell where the log should come from 😕

**Comment by t0rv1c** [comment] 2018-11-22 13:20
@rajivshah3 there is no option to get a debug log?
All I know is that despite the fact that the app acknowledges the Ledger wallet connection, it seems that it's not able to communicate with it. Also, note that at first I had the same issue using Ledger Live until someone suggested sudo with the app (yes, I had already establish the correct udev rules but that wasn't enough). After that everything was smooth. Now, if I start Trinity with sudo I get the same problem reported #621 
I hope this helps.

**Comment by IOTANGLE42** [comment] 2018-11-23 23:24
Had the same issue when I installed Trinity on a Fedora Linux laptop. Trinity opened and I could do the first steps but at "choose your ledger account index" it stucked. I couldn't select an account index.

**Comment by UmbahaSpodPaha** [comment] 2018-12-04 10:16
Having the same problem on Ubuntu 18.10 notebook! When you clicking "Continue" fast - the window "Open IOTA app on your ledger" will flash sometimes but won't go through even if I open IOTA app.

**Comment by rajivshah3** [comment] 2018-12-08 18:26
![image](https://user-images.githubusercontent.com/19519564/49689257-d0605480-faec-11e8-8760-c8fbdf945874.png)
Can you guys try this and see if it's resolved? The command is `wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash`

**Comment by t0rv1c** [comment] 2018-12-08 19:38
@rajivshah3 This is already a prerequisite for Ledger live to be usable on my system. So this was already set a while ago, suggested several times but it doesn't change anything with the current issue. Also, please bear in mind that I can't use ledger live unless I start it with sudo. I suspect that this is the same as with Trinity but trinity has a bug when started with sudo (see post above).

**Comment by IOTANGLE42** [comment] 2018-12-21 15:38
Hi, someone is actively working on this bug? It's 1,5 months since creation and I have no access to my IOTAs since over 1 month :(

**Comment by jamji** [comment] 2019-02-12 22:51
Same issue here on a Ubuntu 18.10 system.

**Comment by IOTANGLE42** [comment] 2019-02-19 10:51
@rajivshah3  This bug is now more than 3 months old and also not assigned to someone. Someone working on that?

**Comment by rajivshah3** [comment] 2019-02-19 14:26
@rihardsgravis would this be fixed by the Ledger app update?

**Comment by vuapo-eth** [comment] 2019-03-03 12:39
Having this issue on Gnome as well.

**Comment by vuapo-eth** [comment] 2019-03-03 12:41
Don't know whether it's related but when starting the AppImage from command line, I'm stuck with the instructions to install libsecret-1-dev (even after doing so).

**Comment by t0rv1c** [comment] 2019-03-19 09:20
Something has changed with the Ledger Iota App because there are new symptoms with the issue. Now if I get to the screen where you choose your ledger account index and click continue, if the ledger app has not been opened yet, it will prompt to open it. As soon as I do that, I will have a Warning message on the ledger that will be available for 1 second and then disappear. When it disappears, the Trinity app will give me a red error pop-up message: "Warning unconfirmed: reopen the Iota app...."
After multiple attempts, I can say that one second is really not enough to scroll and accept the Warning...
These issues have going for so long and I feel like @rajivshah3 has forgotten us.
How old is this bug already????

**Comment by IOTANGLE42** [comment] 2019-03-19 15:26
This problem already exists since months and I contacted the guys multiple
times. Cant access My Wallet on Linux since that time. But no one give a
shit about this problem. Really Strange...

t0rv1c <notifications@github.com> schrieb am Di., 19. März 2019, 10:20:

**Comment by rajivshah3** [comment] 2019-03-19 17:46
This is an issue with [node-hid](https://github.com/node-hid/node-hid) which is used to communicate with the Ledger. If you attempt to reproduce the issue in dev mode, you'll get this error:

```
Error: cannot open device with path /dev/hidraw1
    at new HID (/home/rajiv/trinity-wallet/src/desktop/node_modules/node-hid/nodehid.js:54)
    at Function._callee$ (/home/rajiv/trinity-wallet/src/desktop/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:83)
    at tryCatch (/home/rajiv/trinity-wallet/src/desktop/node_modules/regenerator-runtime/runtime.js:65)
    at Generator.invoke [as _invoke] (/home/rajiv/trinity-wallet/src/desktop/node_modules/regenerator-runtime/runtime.js:303)
    at Generator.prototype.(:1074/anonymous function) [as next] (/home/rajiv/trinity-wallet/src/desktop/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/rajiv/trinity-wallet/src/desktop/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:35)
    at /home/rajiv/trinity-wallet/src/desktop/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:35
    at new Promise (/home/rajiv/trinity-wallet/src/desktop/node_modules/core-js/modules/es6.promise.js:177)
    at Function.<anonymous> (/home/rajiv/trinity-wallet/src/desktop/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:35)
    at Function.open (/home/rajiv/trinity-wallet/src/desktop/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:107)
    at Object.next (/home/rajiv/trinity-wallet/src/desktop/node_modules/@ledgerhq/hw-transport/lib/Transport.js:405)
    at /home/rajiv/trinity-wallet/src/desktop/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:213
    at run (/home/rajiv/trinity-wallet/src/desktop/node_modules/core-js/modules/es6.promise.js:75)
    at /home/rajiv/trinity-wallet/src/desktop/node_modules/core-js/modules/es6.promise.js:92
    at flush (/home/rajiv/trinity-wallet/src/desktop/node_modules/core-js/modules/_microtask.js:18)
    at process._tickCallback (internal/process/next_tick.js:61)
```

> How old is this bug already????

This actually isn't a Trinity bug - there's some issue with the `udev` rules. This is why you will sometimes need to use `sudo` with the Ledger Live app. I'm looking into another workaround because running Trinity with `sudo` isn't ideal

**Comment by t0rv1c** [comment] 2019-03-19 18:36
Hi @rajivshah3 , thanks for your quick reply. Perhaps you could ask what Ledger did to their Ledger Live application about the udev rule because I no longer need to sudo to use the Nano S with Live anymore (I had to for a while).

**Comment by rajivshah3** [comment] 2019-03-19 18:51
I just looked at their repo, and it seems like they now link to a [support article](https://support.ledger.com/hc/en-us/articles/115005165269) detailing how to configure the `udev` rules. We'll use the same approach

**Comment by rajivshah3** [comment] 2019-03-19 20:57
This will be fixed in #1192. I'll change the priority to P2 since there's a support article for it. Sorry for the delay in fixing this issue!

**Comment by IOTANGLE42** [comment] 2019-03-19 21:02
Nice to see a progress :)

Rajiv Shah <notifications@github.com> schrieb am Di., 19. März 2019, 21:57:

**Comment by ghost** [comment] 2019-04-05 16:22
> ![image](https://user-images.githubusercontent.com/19519564/49689257-d0605480-faec-11e8-8760-c8fbdf945874.png)
> Can you guys try this and see if it's resolved? The command is `wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash`

@rajivshah3 This fixed this issue completely for me

**Closed as completed** 2019-04-16 03:42 UTC
Labels: C - Desktop, L - Assigned, P - Linux, P2 - High

**Comment by t0rv1c** [comment] 2019-04-16 18:41
@rajivshah3 I have been using ledger udev rules set up for months now. No problem with Ledger Live but it doesn't work with Trinity. Not sure why you closed this thread. There hasn't been any fix yet...
