### ISSUE TITLE
[Feature] Ledger Nano X Bluetooth support

### ISSUE THREAD

**Issue by viossat** [iotaledger/trinity-wallet#1808] opened 2019-06-18 11:22 UTC
### Description
Add Ledger Nano X Bluetooth support.

### Motivation
Especially useful on mobile.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment] 2019-07-04 12:59
Duplicate of #1932

**Closed as completed** 2019-07-04 12:59 UTC
Labels: T - Feature Request
