### ISSUE TITLE
The ios app can't open the camara to scan seed QR code

### ISSUE THREAD

**Issue by JonaFly** [iotaledger/trinity-wallet#597] opened 2018-11-13 10:33 UTC

**Comment by rajivshah3** [comment] 2018-11-13 18:03
@wjy7551376 would you mind filling out the template? Also, can you verify that Trinity appears in the list under Settings > Privacy > Camera?

**Comment by initharrington** [comment] 2018-11-21 03:48
Hey @rajivshah3 

I figure I would update as I found the same issue.


### Bug description
When using the trinity ios app to scan a QR code to load a seed, the screen is black and the camera does not launch.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: MT602LL/A - iPhone XS Max 256GB
- OS version: 12.1 (16B92)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.5.1 (28)

### Steps To Reproduce
1) Download App
2) Thank you for downloading Trinity screen, click "No, I have one"
3) Enter your seed screen, click the camera icon
4) Loads black screen

### Expected behaviour
What should happen.
The camera should launch within the app to allow me to scan a qr code.

### Actual behaviour
What really happened.
Black screen

### Errors
Nothing happens when it I get to the screen.  No errors.

Issue:
![trinity_issue_qr_code](https://user-images.githubusercontent.com/8240651/48817788-245df180-ed16-11e8-9ef9-32ca3b2043b0.png)

Trinity Privacy Settings:
![trinity_issue_qr_code_camera_settings](https://user-images.githubusercontent.com/8240651/48817791-27f17880-ed16-11e8-9fcc-43b16cc21b39.png)

**Comment by initharrington** [comment] 2018-11-21 03:53
Seems to be similar to #577 as well.

**Comment by cvarley100** [comment] 2018-11-21 18:28
Duplicate of https://github.com/iotaledger/trinity-wallet/issues/577

**Closed as completed by cvarley100** 2018-11-21 18:28 UTC
Labels: P - iOS, C - Mobile, L - Need more information
