### ISSUE TITLE
Error on startup: TypeError: Cannot read property 'ignoreProxy' of null

### ISSUE THREAD

**Issue by cosmicscr** [iotaledger/trinity-wallet#668] opened 2018-11-29 18:22 UTC
### Bug description
App starts up and then immediately throws JS error stacktrace in a modal window.  The stacktrace data cannot be copied and pasted (it should be changed to allow copy/paste).  There is an okay button in the modal window but it's inoperable and the app never loads properly and must be closed down.
 
### Environment Specs
Running on macOS 10.14.1.

Downloaded trinity-desktop-0.4.3.dmg wallet anew, never before installed.
Verified sha256 of 7232ca4e50de765e62410dc74bea70019dad14ecb78f998d7e6e1b43c35ceebd

### Steps To Reproduce
1. Start the app.

### Errors
Attached screenshot of stacktrace.

![screen shot 2018-11-29 at 11 14 26 am](https://user-images.githubusercontent.com/6118944/49242757-c80b6980-f3c8-11e8-862a-37661da8ff81.png)

**Comment by rajivshah3** [comment] 2018-11-29 18:52
Hi @mrcybermac , does this still happen if you move the `Trinity.app` to `/Applications` (looks like it's in `/Applications/Crypto Wallets`)?

**Comment by Chakalaka123** [comment] 2018-11-29 18:58
Btw: Happens with Windows as well

![image](https://user-images.githubusercontent.com/45467419/49244811-fad95000-f410-11e8-9a60-883016531de3.png)

**Comment by cosmicscr** [comment] 2018-11-29 18:58
Hi,  Yes. Just tried it and same error occurs.  Path of
'/Applications/Trinity.app' correctly reflected in stack trace, but same
stack trace otherwise.

**Comment by pawelmiklas** [comment] 2018-11-29 19:06
The same on win 8.1

**Comment by rajivshah3** [comment] 2018-11-29 19:07
@snaqu @Chakalaka123 are you both running a fresh install as well?

**Comment by pawelmiklas** [comment] 2018-11-29 19:12
@rajivshah3 I install wallet on new os so yes.

**Comment by rajivshah3** [comment] 2018-11-29 19:27
Looks like this is a duplicate of #665. We'll release a new build later today/tonight to fix this

**Closed as completed by rajivshah3** 2018-11-29 19:27 UTC
Labels: Duplicate, C - Desktop
