### ISSUE TITLE
50 Mi got stuck – visible but no access

### ISSUE THREAD

**Issue by moedn** [iotaledger/trinity-wallet#1000] opened 2019-01-29 17:43 UTC
First of all: Thank you all for the amazing work that has done! If I can help by providing any additional information, please let me know.

### Bug description
App crashes every time, I try to
- send
- generate a receive address

This is account-specific. Both functions work fine on another account (see ### History)

### Environment Specs

- Manufacturer: LG
- Model: Nexus 5
- OS version: Lineage 14.1
- Trinity version: 0.6.0 (39)

### History
 
1. Noticed that the app only accepts seeds with 81 chars. My seed has 80 so I wanted to shift to a new 81-char-seed
2. generated a seed with 81 chars, logged in through Trinity Wallet (Account Name 'Moe') sent 50 Mi from my desktop wallet (iota light wallet 2.5.7) to that seed from my old seed (80 chars).
3. No transfer after waiting several minutes. I did a reset in my trinity wallet (Settings → Advanced Settings → Reset Wallet). Logged in with the new seed (81 chars), picked a new name ('ruediger'). Repeated the transaction (now with 100 Mi). Transaction succeeded within seconds.
4. Login in a day after I noticed that I have both names in the top panel ('Moe' & 'ruediger') within the same seed. 'Moe' now carries the 50 Mi.
5. I cannot send the 50 Mi from 'Moe' to 'ruediger' as they share the exact same seed. When I try to send the 50 Mi to my old seed (80 chars), the app crashes.
6. When I enter the new seed (81 chars) from my desktop wallet, I only see 100 Mi, which seems to be the account 'ruediger' then.

Any suggestions how I could access the 50 Mi?

cheers

**Comment by rajivshah3** [comment] 2019-01-29 23:37
Hi @moedn 

> Login in a day after I noticed that I have both names in the top panel ('Moe' & 'ruediger') within the same seed. 'Moe' now carries the 50 Mi.

So the `Moe` account reappeared after resetting the wallet? Or is this a different seed with the same account name?

**Comment by moedn** [comment] 2019-01-30 14:03
Hi @rajivshah3 and thanks for the fast reply
 
> So the `Moe` account reappeared after resetting the wallet? Or is this a different seed with the same account name?

The `Moe` account reappeared after resetting the wallet. I have 2 account names on the same seed.

**Comment by laumair** [comment] 2019-01-30 14:33
> Noticed that the app only accepts seeds with 81 chars. My seed has 80 so I wanted to shift to a new 81-char-seed

@moedn You can still use your old seed in Trinity. Light wallet automatically appends `9`s if some characters are missing from your seed. So in order to use your old seed in Trinity, I suggest you manually add `9` at the end of your seed.

**Comment by laumair** [comment] 2019-01-30 14:40
@moedn What happens if you manually sync your `ruediger` account? Does it show the 50 Mi transaction in history?

**Comment by moedn** [comment] 2019-01-30 17:02
Hi @laumair 
> > Noticed that the app only accepts seeds with 81 chars. My seed has 80 so I wanted to shift to a new 81-char-seed
> 
> @moedn You can still use your old seed in Trinity. Light wallet automatically appends `9`s if some characters are missing from your seed. So in order to use your old seed in Trinity, I suggest you manually add `9` at the end of your seed.

Good to know, thanks.

> @moedn What happens if you manually sync your `ruediger` account? Does it show the 50 Mi transaction in history?

When I try a manual sync, the app crashes.
History for 'ruediger' shows 100 Mi, history for 'Moe' shows 50 Mi (see screenshots).
<img src="https://user-images.githubusercontent.com/45949491/51998229-85ddd180-24b8-11e9-878a-cf889e393a7c.jpg" width="300">
<img src="https://user-images.githubusercontent.com/45949491/51998226-85ddd180-24b8-11e9-8962-a2cfe4faa261.jpg" width="300">
<img src="https://user-images.githubusercontent.com/45949491/51998227-85ddd180-24b8-11e9-965d-e0ed3b14513f.jpg" width="300">

**Comment by laumair** [comment] 2019-01-30 17:58
@moedn 

Thanks for providing the info. Can you share the bundle or transaction hash for both 50 Mi and 100 Mi transactions?

**Comment by moedn** [comment] 2019-01-31 17:24
@laumair Thanks for the help!
bundle hashes: 
50 Mi: HEDNXSJNJJFFDRHSEJSYUKYYVGRJE9GHALBZQGSOEDG9GUYCNBWQVAKXJXBXJKJ9SDNHBCIHOTVSTQGWA

100 Mi: 
JKZNKNFODCFBPBTBPA9YIISBIDTM9CZKXOFWDDGREJCR9SC9RNKTPGZAVIVGNIJPTSPKTBEOUAWKILLNC

**Comment by laumair** [comment] 2019-01-31 22:52
Thanks. Wanted to make sure both transactions were confirmed. 

I think that the problem is specific to `Lineage 14.1` where it doesn't remove the data from `AsyncStorage` on wallet reset.I'll investigate and fix the issue but you'll have to reinstall the app to fix this issue right now. 

**Please make sure you've backed up your seeds.**

**Comment by moedn** [comment] 2019-02-01 17:20
@laumair thanks for the effort!
I did a snapshot for `ruediger` (100 Mi), and for `Moe` (50 Mi). `ruediger` worked out of the box, for `Moe` the app first showed `0 i, is that correct?` → `No` → crash. After restart: `50 Mi, is that correct?` → `Yes` → alright!
When I repeat the snapshot for `Moe`, it suggests me  `0 i` again → `No` → crash → restart → `50 Mi` → `Yes` → cool. I can repeat that as much as I want.

I reinstalled the app. `Moe` (and the 50 Mi) disappeared. `ruediger` is now the only visible account. The 50 Mi are permanently lost?

**Comment by laumair** [comment] 2019-02-04 16:41
@moedn No it's not possible they are lost. After reinstallation, can you perform a snapshot transition on your `ruediger` account?

**Comment by moedn** [comment] 2019-02-06 12:55
@laumair snapshot will only detect a balance of `100 Mi`. I repeated 6 times (`ruediger` account)

**Comment by laumair** [comment] 2019-02-07 11:15
@moedn Do you have `
AQSJISVWJQYCPASQXGIAEHZKYWVNTKIXNLWR9FHGKBIWKJBBRBBDDWJVTCBSUPWUDYJCX9OVYOCUARDSA` address in your wallet? 

You can check that in Settings > Account Management > View Addresses.

**Comment by moedn** [comment] 2019-02-11 12:33
@laumair I don't (see screenshot). Is it possible to add it?
<img src="https://user-images.githubusercontent.com/45949491/52563415-a2a3ce80-2e01-11e9-97ec-e8021febbc12.jpg" width="300">

**Comment by laumair** [comment] 2019-02-12 18:56
@moedn Not possible to manually add an address. It's automatically generated from your seed. 

Are you registered on [IOTA discord](https://discordapp.com/invite/AnXGeBr) ? I'll need your test seed to debug what's wrong. My discord handle is `Umair Sarfraz [IF]`.

**Comment by moedn** [comment] 2019-07-06 10:57
@laumair sorry for the immense delay. I wrote you on discord.

**Comment by cvarley100** [comment] 2019-07-08 12:56
As this is a specific case I'll close this one. Please continue the discussions on Discord.

**Closed as completed by cvarley100** 2019-07-08 12:56 UTC
Labels: C - Mobile, L - Need to reproduce, E - Functional
