### ISSUE TITLE
blue screen after POW. 

### ISSUE THREAD

**Issue by EelkeRitsma** [iotaledger/trinity-wallet#815] opened 2018-12-16 12:21 UTC
I have sent iotas on 2 occasions yesterday (15 dec 2018) and after both times my screen froze and just showed the blue background of the trinity wallet. This occurs right after the "Broadcasting" message comes up.

After closing trinity and starting it up again i saw the message the iotas were sent.

I am running on Windows 10 pro. 
The trinity version is 04.4, downloaded on 15 dec. 2018 via trinity.iota.org

### Bug description
A general description of the bug.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model: 
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
What should happen.

### Actual behaviour
What really happened.

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Note**
The feature request will probably be integrated faster if you do a pull request for it.
If you want to discuss the feature before you actually write the code you are welcome to do it by first submitting an issue.

### Description
Briefly describe the feature you want.

### Motivation
Explain why this feature is needed.

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Yes/No.

**Comment by rihardsgravis** [comment] 2018-12-16 12:36
Duplicate of #798

**Closed as completed by rihardsgravis** 2018-12-16 12:36 UTC
