### ISSUE TITLE
Missing translation in dropdown menu "All"

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#653] opened 2018-11-29 01:43 UTC
### Bug description
"All" is translated as selected option but not translated in dropdown menu on options TO BE selected.
(see screenshot)
![all - dropdown](https://user-images.githubusercontent.com/35224101/49193757-97074680-f380-11e8-8980-d0cdd713345d.png)

### Environment Specs
PC - Win7

- Trinity version: 0.4.2

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
Both - selected item "All" and item to be selected "all" should be translated

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment] 2018-11-29 06:23
Duplicate of https://github.com/iotaledger/trinity-wallet/issues/519#issuecomment-440826056

**Closed as completed by rajivshah3** 2018-11-29 06:23 UTC
Labels: Duplicate
