### ISSUE TITLE
The app icon not displayed

### ISSUE THREAD

**Issue by vincenzopalazzo** [iotaledger/trinity-wallet#887] opened 2019-01-07 10:13 UTC
Bug description
The app icon not displayed

Environment Specs
What device are you running Trinity on?

Manufacturer: Del
Model: E5270
OS version: Linux mint 19
What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

Trinity version: 0.4.6

**Comment by rajivshah3** [comment] 2019-01-07 16:09
Duplicate of https://github.com/iotaledger/trinity-wallet/issues/821

**Closed as completed by rajivshah3** 2019-01-07 16:09 UTC
Labels: Duplicate, C - Desktop
