### ISSUE TITLE
Feature Request: Offline signing of transactions

### ISSUE THREAD

**Issue by K2APacific** [iotaledger/trinity-wallet#2016] opened 2019-07-12 02:57 UTC
### Description
The ability to sign an IOTA transaction on an offline air gaped computer. Bitcoin has several wallets that can do this using a "watch only wallet" that only generates the transaction online, but the signing for the transaction happens on an offline air gaped computer.

### Motivation
Offline signing means a users seed will never go online. The user can never be phished, or the victim of a key logger virus or a screen capture virus. The user can also verify the transaction before it is broadcast, so that the user will know in plain human readable form what the transaction will do once broadcast (in other words the user can not be tricked into signing something malicious with their seed)

### Requirements
Simple offline signing of IOTA transactions

### Open Questions (optional)
There are a few projects already on Github that allow for offline signing of IOTA transactions. Perhaps that can be a guide for the Trinity wallet devs. For example,
https://github.com/looploooop/iota-send-offline
https://github.com/ixuz/iota-offline

Thanks for a great wallet !

**Comment by dreamfony** [comment] 2019-07-17 15:38
Issue #647 already has same feature request.
https://github.com/iotaledger/trinity-wallet/issues/647

I would maybe expand on this and ask:

Is it possible to "load" encrypted seed file to trinity?
@cvarley100 can you point me to part of the source code where TW encryptes seed.
It would also be good to create this file on an offline airgapped computer and transfer it to where TW is.

**Comment by rajivshah3** [comment] 2019-07-18 15:06
> Is it possible to "load" encrypted seed file to trinity?

Yes, we call this a SeedVault. It is an encrypted KeePass-compatible file that stores your seed

> can you point me to part of the source code where TW encryptes seed.

For desktop, most of the code is in [src/desktop/src/libs/SeedStore/Keychain.js](https://github.com/iotaledger/trinity-wallet/blob/develop/src/desktop/src/libs/SeedStore/Keychain.js) and [src/desktop/src/libs/crypto.js](https://github.com/iotaledger/trinity-wallet/blob/develop/src/desktop/src/libs/crypto.js)

**Comment by cvarley100** [comment] 2019-09-11 14:48
Duplicate of #647

**Closed as completed by cvarley100** 2019-09-11 14:48 UTC
Labels: T - Feature Request
