### ISSUE TITLE
"Could not broadcast transfer" appearing every minute

### ISSUE THREAD

**Issue by ratiodep** [iotaledger/trinity-wallet#1607] opened 2019-05-24 14:35 UTC
### Bug description
A general description of the bug.

Error log: " Already spent from addresses: (...)"

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Dell
- Model: Precision 7720
- OS version: Win 7 64 bit

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.51

### Steps To Reproduce
1. Open Trinity

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Comment by rajivshah3** [comment] 2019-05-24 14:44
Duplicate of #1386

**Closed as completed by rajivshah3** 2019-05-24 14:44 UTC
Labels: T - Bug, Duplicate, C - Desktop

**Comment by ratiodep** [comment] 2019-05-24 15:09
Sorry

Am Fr., 24. Mai 2019 um 16:44 Uhr schrieb Rajiv Shah <
notifications@github.com>:
