### ISSUE TITLE
Error fetching account information when using Ledger

### ISSUE THREAD

**Issue by farl4web** [iotaledger/trinity-wallet#838] opened 2018-12-21 08:38 UTC
**PLEASE NOTE** If you are experiencing this issue, please fill out this form:

**Make sure you complete all the steps described.** (NB. Resetting your wallet in step 4 is not dangerous. All you need to reinitialise the wallet is your Ledger and account index number)

```
1. Trinity version:
2. Ledger device IOTA app version (IOTA>About>Version):
3. OS and version:
4. Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n):
5. Ledger uses an Index that is not 0 (y/n):
6. Can you successfully add a non-Ledger account (y/n):
7. You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n): 
8. What error is appearing on the loading screen:
9. What happens after the error appears:
10. Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n):
```

------

I cannot login with my Ledger on Trinity Desktop wallet. I get error that it's not able to connect to the node. I updates to the latest version v.0.4.5 on my Mac. I am using macOS 10.13.6. I restarted everything a few times. Made sure my ledger was up-to-date. 

I tried different nodes and disabled/enabled "Use system proxy". 

Can someone help?
![schermafbeelding_2018-12-20_om_20 44 42](https://user-images.githubusercontent.com/2842652/50333007-2b8a4200-0504-11e9-8ffa-8321224593a7.png)
![schermafbeelding_2018-12-20_om_20 44 50](https://user-images.githubusercontent.com/2842652/50333008-2b8a4200-0504-11e9-825b-054520fdca54.png)

**Comment by rajivshah3** [comment] 2018-12-22 02:44
Hi @farl4web , have you tried different nodes?

**Comment by farl4web** [comment] 2018-12-24 09:05
Yes, I did. Some were advised on Discord. But nothing changes...

**Comment by rajivshah3** [comment] 2018-12-25 06:38
@farl4web is this reproducible with a new, unused seed?

**Comment by rajivshah3** [comment] 2018-12-25 07:56
@steffenroeber looks like you're having the same issue. Is this reproducible with a new, unused seed?

**Comment by steffenroeber** [comment] 2018-12-25 09:37
The error log says: ' Incorrect seed name'

**Comment by steffenroeber** [comment] 2018-12-25 11:36
> 
> 
> @steffenroeber looks like you're having the same issue. Is this reproducible with a new, unused seed?

No, a new seed works.

**Comment by rajivshah3** [comment] 2018-12-25 18:35
@steffenroeber can I ask what the name of the affected account is? We've had a few bugs relating to numbers or certain characters in the account name

**Comment by steffenroeber** [comment] 2018-12-25 18:38
What do you mean with ,name of amount'?

Gesendet von Yahoo Mail auf Android 
 
  Am Di., Dez. 25, 2018 at 19:35 schrieb Rajiv Shah<notifications@github.com>:   
@steffenroeber can I ask what the name of the affected account is?

**Comment by rajivshah3** [comment] 2018-12-25 18:39
For example, "Main Account" or "Second Account". It's a name you give for the account in Trinity which appears in the left side of the app

**Comment by steffenroeber** [comment] 2018-12-25 18:43
Cannot remember exactly. Where can I find this name without logging in?

 

Von: Rajiv Shah <notifications@github.com> 
Gesendet: Dienstag, 25. Dezember 2018 19:40
An: iotaledger/trinity-wallet <trinity-wallet@noreply.github.com>
Cc: steffenroeber <steffenroeber@yahoo.de>; Mention <mention@noreply.github.com>
Betreff: Re: [iotaledger/trinity-wallet] Cannot login new Trinity desktop wallet (#838)

 

For example, "Main Account" or "Second Account". It's a name you give for the account in Trinity which appears in the left side of the app

**Comment by rajivshah3** [comment] 2018-12-25 18:44
Ah right, you won’t be able to see that without logging in. Do you remember if the account name had numbers or brackets (`[]`)? It’s fine if you don’t remember

**Comment by steffenroeber** [comment] 2018-12-25 18:46
As far as I can remember, I only used letters.

**Comment by steffenroeber** [comment] 2018-12-25 18:47
And I'm pretty sure, I've not used any of: brackets (`[]`)

**Comment by steffenroeber** [comment] 2018-12-25 18:48
Maybe a 'space' char but not sure.

**Comment by steffenroeber** [comment] 2018-12-25 18:58
I recovered my wallet by replacing the %appdata%\Roaming\Trinity folder by an older one (I made a copy recently). Now I have one that works (the older one) and one that fails to login.
Account names (3) are 'Steffen', 'Steffen Ledger' and 'Janice'
Does this help?

**Comment by steffenroeber** [comment] 2018-12-25 18:58
The new one has following error log:
 Ledger device: Invalid INS command (0x6d00)
 Request Error: Request timed out.

**Comment by rajivshah3** [comment] 2018-12-26 20:30
@farl4web @steffenroeber could you both see if the issue persists in v0.4.6?

**Comment by steffenroeber** [comment] 2018-12-26 21:09
Hi,

problem still exists in 0.4.6.

 

Von: Rajiv Shah <notifications@github.com> 
Gesendet: Mittwoch, 26. Dezember 2018 21:30
An: iotaledger/trinity-wallet <trinity-wallet@noreply.github.com>
Cc: steffenroeber <steffenroeber@yahoo.de>; Mention <mention@noreply.github.com>
Betreff: Re: [iotaledger/trinity-wallet] Cannot login new Trinity desktop wallet (#838)

 

@farl4web <https://github.com/farl4web>  @steffenroeber <https://github.com/steffenroeber>  could you both see if the issue persists in v0.4.6?

**Comment by abasees** [comment] 2018-12-30 08:58
Can confirm same issues with Ledger Nano S.

I've tried troubleshooting by selecting over 10 different recommended nodes and turning off the proxy setting however no luck.

Interestingly, I did manage to log in to the wallet initially however after leaving it open inactive for too long I had to re-sign in and that is when issue presented itself.

**Comment by dyrdon** [comment] 2018-12-30 22:05
I have the same issue aswell..
Same error as above or something with Ledger App Not opened by User error - But only in Log on the main screen it says „Node error“ and i tried all of them ..It seems like Trinity is not recognising the App properly.

Trinity and Ledger up to Date.
Windows 10

**Comment by farl4web** [comment] 2019-01-06 18:41
Problems is still there. I can't access my accounts. 

Error log:  Ledger device: App has not been initialized by user (0x6986)

**Comment by farl4web** [comment] 2019-01-06 19:38
After trying several nodes. I now found a now which is working: https://nodes.thetangle.org:443/. After that I can finally login after weeks of trying several nodes. Welcome to IOTA! ;)

**Comment by benbeton** [comment] 2019-02-01 05:04
any update here? I'm facing the same issue.

**Comment by rajivshah3** [comment] 2019-02-01 05:35
@benbeton are you getting any error messages?

**Comment by benbeton** [comment] 2019-02-02 18:53
@rajivshah3 I'm getting the same error messages as seen in the first post. 
Running Trinity 0.4.6 with Ledger Nano S (latest FW) and latest macOS

**Comment by Robbobrob** [comment] 2019-02-07 22:06
Anyone of the developers around to to comment on this issue? Is there worked on and when a solution can be expected? I also tried above suggestions, even back to v4.5 but that doesn't work either.

**Comment by rajivshah3** [comment] 2019-02-08 05:33
@Robbobrob what OS are you running, and are you getting any error messages?

**Comment by Robbobrob** [comment] 2019-02-08 09:17
MacOS 10.14.3 (latest). I got the same messages as the start of this tread screenshots.
Now Trinity did work before though. Maybe Mac OS updates caused conflicts? (on 3- and 8 February there were MacOS updates for 10.14.3)

**Comment by dyrdon** [comment] 2019-02-08 16:26
Hello,

I found out trying to update my Ledger Firmware, that my usb drivers was not working properly. I updated my drivers ( not through the Windows auto Update, but specifically for my computer ) and everything is working just fine right now.
Trying other usb ports might help already.
Good luck and greetings.

**Comment by Robbobrob** [comment] 2019-02-09 23:08
My Ledger was uptodate and it works also fine with other Ledger-apps so no issue with usb ports (and thus the drivers of it). Then im not sure if you can manually update Mac hardware drivers like you can on a Windows system; but since the usb ports work fine i don't think there lies the problem.
I did tried other ports though but no result.
But thanks for your suggestions.

**Comment by GoodHabitx** [comment] 2019-02-12 18:57
I'm having this exact same issue. I haven't been able to log into my trinity wallet all day.

**Comment by Robbobrob** [comment] 2019-02-28 06:26
I see Desktop 5.0 is in testphase; when can a release version be expected? - and is a fix for this  Ledger wallet issue included?
And/or will the Ledger-app be also updated?

**Comment by Robbobrob** [comment] 2019-03-04 00:27
Surprisingly today wallet access. But transactions problematic: even transaction is placed on Tangle (so receiver has incoming), no confirmation. When i promote the transaction i get message like  'possibly no connection to device'. After several attempts (incl disconnection Ledger etc) finally done. Maybe something wrong with the Ledger IOTA-app?

**Comment by Iwanth** [comment] 2019-03-23 17:35
Hi, I have the same issue. I stored my IOTA coins on a hard ledger using trinity. Now I am not able to log in. It is said: error fetching account information. I tried all available different nodes, but all nodes are returned while fetching my account information. I also disabled my system proxy, but that didn't help as well. I tried to get into contact with Trinity, but a 404 error message was shown. Can anybody help me out here?

**Comment by kyrothespacecat** [comment] 2019-03-26 14:36
Same error. MacOS 10.14.3 (18D109), Trinity 0.4.6, Ledger Nano S. Already tried to change nodes, disable user system proxy.

**Comment by FlensGold** [comment] 2019-03-28 19:32
Also having the same problem. Already updated Ledger Nano S to latest FW, also using Trinity 0.4.6.
Deleting the "APPDATA" Folder allows me to login and create new wallets, but have no access to those created earlier having my IOTA.

**Comment by lucaspukus** [comment] 2019-03-31 22:42
Im having the same problem with latest Mac OS & trinity wallet 0.4.6.
Was this issue resolved?

**Comment by jtpavlock** [comment] 2019-04-01 01:07
Having same issue trinity 0.4.6 Windows 10

**Comment by cyrilstandke** [comment] 2019-04-01 09:31
Same problem here, windows 10, trinity 0.4.6
I no longer have access to my IOTA stored on Ledger Nano S with Trinity!!!

**Comment by rihardsgravis** [comment] 2019-04-01 09:57
@looseboy2 @jtpavlock @lucaspukus @FlensGold @kyrothespacecat  and others who who have encountered the problem – could you, please, fill this info. That would greatly help to mitigate the issue:
```
Trinity version:
Ledger device IOTA app version (IOTA>About>Version):
OS and version:
Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n):
Ledger uses an Index that is not 0 (y/n):
Can you successfully add a non-Ledger account (y/n):
You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n): 
What error is appearing on the loading screen:
What happens after the error appears:
Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n):
```

**Comment by lucaspukus** [comment] 2019-04-01 10:37
I. have not pressed the "reset" button as it says my wallet will be wiped of all data. I don't really want to lose my coins

**Comment by lucaspukus** [comment] 2019-04-01 11:29
OK so I sorted it out.
I reset my wallet, reopened & added my old key when asked to create an account. Then created another account using my ledger nano & it worked. Deleted the first account I created & now I have my Ledger nano account with full balance showing

**Comment by gisinator** [comment] 2019-04-01 18:10
Same problem here. Running Ubuntu 18.04.2 and I could successfully login to my account via Trinity 0.4.6 and Ledger Nano S in the afternoon.

Then upgraded Ledger firmware, reinstalled IOTA app and since then no logins any more. I get the same error msg as everybody here: "Error fetching account information"

I tried almost all nodes available, turned proxy on and off but still: nothing. Kinda frustrating...

**Comment by cvarley100** [comment] 2019-04-01 18:13
@gisinator Please fill out the form shared by Rihards. It will help us to debug the issue

**Comment by gisinator** [comment] 2019-04-01 18:23
Trinity version: 0.4.6
Ledger device IOTA app version (IOTA>About>Version): 0.4.2
OS and version: Ubuntu 18.04.02
Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): This did the trick. I remember I used the 0 index for my initial account. So, after resetting I chose index 1 for a new account. It worked, but - of course - showed a zero-balance. Then I clicked on "add new account", chose the 0 index, and now I can see my initial balance.

**Comment by kyrothespacecat** [comment] 2019-04-02 07:55
> Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n):
Trinity: latest version
Ledger: latest version
OS: mac os latest version
Ledger IOTA app: latest version
 
– didn’t reset. i will lose my money if i do it. Or will not?
– if Index is seed, so it is not 0
– didn’t tried add non-ledger
– "Error fetching account information”
– nothing happens, nothing generated

**Comment by Libitinarius** [comment] 2019-04-02 14:44
Hi I have the same issue, I cna't log in to ANY node, proxy is OFF,

Trinity version:  -----> v04.6beta
Ledger device IOTA app version (IOTA>About>Version): ----->0.4.2
OS and version: Windows 10 Pro 10.0.174
Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): I didn't try
Ledger uses an Index that is not 0 (y/n): -----> YES
Can you successfully add a non-Ledger account (y/n):
You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n): 
What error is appearing on the loading screen:
What happens after the error appears:
Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n):

**Comment by cyrilstandke** [comment] 2019-04-02 15:30
Hi,

After i tried to repro the issue it's been resolved by itself. I didn't change anything.
Now i can login again...

However, I will be interested in the solution found to solve this problem as i'm still afraid it can happen again to me.

Regards,

________________________________
De : Libitinarius <notifications@github.com>
Envoyé : mardi, 2 avril 2019 14:44
À : iotaledger/trinity-wallet
Cc : looseboy2; Mention
Objet : Re: [iotaledger/trinity-wallet] Error fetching account information when using Ledger (#838)


Hi I have the same issue, I cna't log in to ANY node, proxy is OFF,

Trinity version: -----> v04.6beta
Ledger device IOTA app version (IOTA>About>Version): ----->0.4.2
OS and version: Windows 10 Pro 10.0.174
Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): I didn't try
Ledger uses an Index that is not 0 (y/n): -----> YES
Can you successfully add a non-Ledger account (y/n):
You can get pass Choose your Ledger account index view successfully and pick an account name: (y/n):
What error is appearing on the loading screen:
What happens after the error appears:
Is Ledger generating addresses on the Loading screen (Generating Addr... message appears several times on your Ledger device before the error appears) (y/n):

**Comment by rajivshah3** [comment] 2019-04-02 15:36
Hi @looseboy2 , would you still be able to fill out the template with as much information as you can remember? This might help us isolate the cause of the issue

**Comment by cyrilstandke** [comment] 2019-04-02 18:23
Hi,

Here we go...


Trinity version: v0.4.6

Ledger device IOTA app version (IOTA>About>Version): v0.4.2

OS and version: Windows 10, 64 bit, build 1809

Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): no I didn’t reset my wallet

Ledger uses an Index that is not 0 (y/n): y

Can you successfully add a non-Ledger account (y/n): no I haven’t tried

You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n): n

What error is appearing on the loading screen: Node error: The node returned an error while fetching your account information. If your problem persists, try changing node or disabling your system proxy in Trinity Settings.

What happens after the error appears: Trinity app goes back to login screen

Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n):n

________________________________
De : Rajiv Shah <notifications@github.com>
Envoyé : mardi, 2 avril 2019 15:36
À : iotaledger/trinity-wallet
Cc : looseboy2; Mention
Objet : Re: [iotaledger/trinity-wallet] Error fetching account information when using Ledger (#838)


Hi @looseboy2<https://github.com/looseboy2> , would you still be able to fill out the template with as much information as you can remember? This might help us isolate the cause of the issue

**Comment by Octo77** [comment] 2019-04-04 09:00
I have the same problem, havent been able to log in for weeks!, allways fault with trying to get account information from the node, tries more than 20 nodes, changing proxy, nothing works. 
Please help, this is not good for me or IOTA wallet reliability!

using windows 10, latest Trinity wallet, connect with Ledger.

**Comment by cvarley100** [comment] 2019-04-04 10:20
@Octo77 Please fill out the form

**Comment by cvarley100** [comment] 2019-04-04 10:27
@jtpavlock @lucaspukus @FlensGold @benbeton @iwanth @dopefleeky Please can you fill out the template we shared. It will greatly help us to debug this issue 🙏

**Comment by rajivshah3** [comment] 2019-04-04 10:34
@cvarley100 the issue went away for @looseboy2 so I just asked them to fill out what they remember

**Comment by jtpavlock** [comment] 2019-04-04 19:31
@cvarley100 It started working after nothing special on my end I just gave up one night and woke up the next morning to it working on the first try. Unfortunately, I can't remember the specifics nor did I try much debugging beforehand.

Sorry I couldn't be of more help.

**Comment by FlensGold** [comment] 2019-04-04 22:11
1. Trinity version: v0.4.6Beta
2. Ledger device IOTA app version (IOTA>About>Version): 0.4.2
3. OS and version: Windows 10 Prof
4. Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): didn't reset wallet
5. Ledger uses an Index that is not 0 (y/n): not sure, guess it was 1 or 0
6. Can you successfully add a non-Ledger account (y/n):
7. You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n):  did not try
8. What error is appearing on the loading screen:
Node error: The node returned an error while fetching your account information. If your problem persists, try changing node or disabling your system proxy in Trinity Settings.
9. What happens after the error appears: Trinity app goes back to login screen
10. Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n): y

**Comment by kon75** [comment] 2019-04-06 23:11
Same issues here.
1. Trinity version: v0.4.6 beta
2. Ledger device IOTA app version (IOTA>About>Version): 0.4.2
3. OS and version: MacOS 10.14.4
4. Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): have not tried to reset yet
5. Ledger uses an Index that is not 0 (y/n): No, it is not 0
6. Can you successfully add a non-Ledger account (y/n): have not tried
7. You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n):  n/a unable to login
8. What error is appearing on the loading screen: "Error fetching account information. Trying again with a different node." followed by "The node returned an error while fetching your account information. If the problem persists, try changing node or disabling your system proxy in Trinity setting." I have tried multiple nodes and proxy enabled/disabled
9. What happens after the error appears: Returns back to the logon screen
10. Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n): no output on ledger nano S

Currently using node https://nodes.thetangle.org:443 (appears to respond correctly when selecting it)
Let me know what other information I can provide.

**Comment by Libitinarius** [comment] 2019-04-09 17:38
Any news or solutions ?

**Comment by cvarley100** [comment] 2019-04-09 18:20
Hi @libitinarius we are currently investigating this issue. We’ll let you know here any developments.

**Comment by stefanowitschdev** [comment] 2019-04-13 13:25
Same issue here:

Trinity version: v0.4.6 beta
Ledger device IOTA app version (IOTA>About>Version): 0.4.2
OS and version: Windows 10 (release 1809)
Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): have not yet tried resetting wallet
Ledger uses an Index that is not 0 (y/n): n (I am using Seed Index 0)
Can you successfully add a non-Ledger account (y/n): where can I try that without getting into the wallet
You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n): n
What error is appearing on the loading screen: "Error fetching account information Trying again with a different node... "  then shortly after: "The node returned an error while fetching your account information. If your problem persists, try changing node or disabling your system proxy in Trinity Settings".
What happens after the error appears: Trinity again returns to the dialog alsking for the Trinity Password.
Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n): n

Other notes: I have tried multiple nodes already and I have also disabled the system proxy in Trinity advanced settings. Using Ledger Nano S Firmware 1.5.5.

**Comment by laumair** [comment] 2019-04-15 10:09
@stefanowitschdev What error exactly do you see in your Error log?

**Comment by kon75** [comment] 2019-04-18 20:51
> Same issues here.
> 
> 1. Trinity version: v0.4.6 beta
> 2. Ledger device IOTA app version (IOTA>About>Version): 0.4.2
> 3. OS and version: MacOS 10.14.4
> 4. Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): have not tried to reset yet
> 5. Ledger uses an Index that is not 0 (y/n): No, it is not 0
> 6. Can you successfully add a non-Ledger account (y/n): have not tried
> 7. You can get pass _Choose your Ledger account index_ view successfully and pick an account name: (y/n):  n/a unable to login
> 8. What error is appearing on the loading screen: "Error fetching account information. Trying again with a different node." followed by "The node returned an error while fetching your account information. If the problem persists, try changing node or disabling your system proxy in Trinity setting." I have tried multiple nodes and proxy enabled/disabled
> 9. What happens after the error appears: Returns back to the logon screen
> 10. Is Ledger generating addresses on the Loading screen (_Generating Addr..._ message appears several times on your Ledger device before the error appears) (y/n): no output on ledger nano S
> 
> Currently using node https://nodes.thetangle.org:443 (appears to respond correctly when selecting it)
> Let me know what other information I can provide.

Any other forums discussing this issue? Need help in getting this resolved.

**Comment by dopaminedecay** [comment] 2019-04-28 09:59
same problem here:

1. Trinity version: 0.4.6
2. Ledger device IOTA app version (IOTA>About>Version): 0.4.2
3. OS and version: MAC OS Sierra 10.12.6
4. Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): didn’t´t try
5. Ledger uses an Index that is not 0 (y/n): no
6. Can you successfully add a non-Ledger account (y/n): didn’t´t try
7. You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n): n/a unable to login
8. What error is appearing on the loading screen: "Error fetching account information. Trying again with a different node." followed by "The node returned an error while fetching your account information. If the problem persists, try changing node or disabling your system proxy in Trinity setting." I have tried multiple nodes and proxy enabled/disabled
9. What happens after the error appears: back to login screen
10. Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n): no output on ledger nano s

**Comment by dopaminedecay** [comment] 2019-05-08 16:22
Hello,
Still the same issues with Trinity Wallet Version 0.5. 
I was hoping it would be fixed with the update. 
Is there any progress in solving this issue? I need to access my wallet. 
Thank you

**Comment by derlefti** [comment] 2019-05-09 09:59
In my case step 4 (resetting the wallet) solved the problem. The funds were NOT lost via the reset.

**Comment by Noigu99** [comment] 2019-05-10 19:12
Same issue, please help!

**Trinity version:** 0.5.0 beta
**Ledger device IOTA app version (IOTA>About>Version):** 0.4.2
**OS and version:** Windows 10 PRO
**Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n):** didn't reset, as I'm afraid to be asked for some info I don't know/remember!
**Ledger uses an Index that is not 0 (y/n):** how do I know this?
**Can you successfully add a non-Ledger account (y/n):** don't know how to do it
**You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n):** unable to login!
**What error is appearing on the loading screen:**  "Error fetching account information. Trying again with a different node." followed by "The node returned an error while fetching your account information. If the problem persists, try changing node or disabling your system proxy in Trinity setting." I have tried multiple nodes and proxy enabled/disabled
**What happens after the error appears:** back to login screen
**Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n):** no output on ledger nano s

**Comment by cvarley100** [comment] 2019-05-10 19:19
@Noigu99 If you wrote down your Ledger account index (default is 0) then resetting Trinity is not a problem. 

Can you check that your device time is correct?

**Comment by Noigu99** [comment] 2019-05-10 19:51
I don't remember at all regarding the Index, that's why I'm afraid of resetting it. Time is right and by the way I could access the wallet multiple times before 2-3 weeks since when the problem arose.

**Comment by Lupomannaro** [comment] 2019-05-12 19:15
Hi, same problem, what to do? 

Error fetching account information. Trying again with a different node." followed by "The node returned an error while fetching your account information. If the problem persists, try changing node or disabling your system proxy in Trinity setting." I have tried multiple nodes and proxy enabled/disabled

**Comment by FlensGold** [comment] 2019-05-16 16:06
Any news about this? I have quite a lot IOTA in my wallet and would be happy if I could access them again...
I have been using the IOTA Light wallet earlier and moved to trinity hoping that it would be secure in combination with a Ledger Nano....I am afraid this was a big mistake :-(

Already updated to Trinity 0.5, same problem...

**Comment by cvarley100** [comment] 2019-05-16 16:08
@Noigu99 The default index is 0. It tells you to write down the index if you change it. If you are comfortable doing so, then I suggest resetting the wallet and trying again.

@Lupomannaro @FlensGold Can you check that your computer's time is correct?

**Comment by FlensGold** [comment] 2019-05-16 16:10
Maybe a stupid question: Where can I check the time of the device (Ledger Nano S)?

**Comment by cvarley100** [comment] 2019-05-16 16:13
Apologies @FlensGold. I mean the time on your computer OS.

**Comment by FlensGold** [comment] 2019-05-16 16:14
No problem, but the time is in synch with time.org
It is automatically set by windows (option is on)

I just resetted my wallet (Settings>Advanced Settings>Reset wallet) and after restart of trinity I could set up a new wallet in combination with Ledger. I choosed Index 0 since as far as I remember that was the one I used earlier. After a while trinity started with a balance of 0 which also did not change after I synched it.

Before I resetted it I saved the AppData\Roaming\Trinity Folder and now copied it back since resetting obviously also did not solve it...so I am getting the "old error" now.

**Comment by Lupomannaro** [comment] 2019-05-16 18:28
Time is correct, so any solutions?

**Comment by cvarley100** [comment] 2019-05-16 18:57
@Lupomannaro @FlensGold Did either of you use the first Trinity Ledger release (0.4.0-alpha)?

**Comment by Lupomannaro** [comment] 2019-05-16 20:20
Not sure, it was first, but had no problems before, error appeared 3 weeks ago

**Comment by dopaminedecay** [comment] 2019-05-16 20:37
What does the error log say (Trinity>Error log) ?

**Comment by Lupomannaro** [comment] 2019-05-16 20:54
Leadger device: App has not been initialised by user (0x6986)

**Comment by dopaminedecay** [comment] 2019-05-16 21:13
I had the same issue. The error log in the Trinity Wallet said: 
**App has not been initialised by user (0x6986)**

In that case you need to initialize the Ledger device by opening the IOTA App on the Ledger Nano S
and accepting the warning shown on the device when connected to Trinity Wallet. 
You need to press both Ledger buttons to confirm. 
(I had to scroll down on the Ledger device with one button before Ledger device has shown the small lines, below the buttons on the display, that appear when you can confirm.) 

This seems to be a Ledger problem, not a Trinity problem.

**Comment by Lupomannaro** [comment] 2019-05-17 04:47
Thank you, i’ll will try this out

**Comment by Lupomannaro** [comment] 2019-05-19 20:19
it helped to solve the problem, thank you!

**Comment by FlensGold** [comment] 2019-05-20 17:34
> I had the same issue.
> 
> You just need to initialize the Ledger device by opening the IOTA App and accepting the warning shown on the device. You need to press both Ledger buttons.
> I had to scroll down with one button before Ledger has shown the small lines below the buttons on the display.
> 
> This seems to be a Ledger problem, not a Trinity problem.

Sorry, I do not get this, maybe you could explain it again? Are you talking about the "IOTA App" on the Ledger Nano S? Where can I initialize it again?

**Comment by dopaminedecay** [comment] 2019-05-20 19:37
Yes, the IOTA App on the Ledger Nano S.
I edited my previous comment. Hope its more clear to understand now.

**Comment by FlensGold** [comment] 2019-05-20 19:47
I am feeling a bit stupid.
When accessing the IOTA APP on the Ledger (using both buttons) I get into a menu with 3 options: 
IOTA, About and Exit: App.  
I can browse that menu by using 1 button and have to use both buttons to access one option (Option IOTA is only a title, so nothing happens, Exit gets back to the wallet menu. I still have no clue where to find those "small lines" :-(

**Comment by dopaminedecay** [comment] 2019-05-20 20:14
> I am feeling a bit stupid.
> When accessing the IOTA APP on the Ledger (using both buttons) I get into a menu with 3 options:
> IOTA, About and Exit: App.
> I can browse that menu by using 1 button and have to use both buttons to access one option (Option IOTA is only a title, so nothing happens, Exit gets back to the wallet menu. I still have no clue where to find those "small lines" :-(

yes, the warning that you have to accept/confirm to initialize the device just flashes on the devices screen for a very short while. I didn´t noticed it first few times either. So as soon as this warning appeared, i clicked one of the ledger buttons few times to scroll down in the warning to confirm.  Hope it works for you.

**Comment by FlensGold** [comment] 2019-05-20 21:23
I do not get it. Tried several times, never got to that option. Do you have trinity started while testing it?

If it is important: My Trinity error log says " Incorrect Ledger device or changed mnemonic".

**Comment by cvarley100** [comment] 2019-05-21 08:35
> If it is important: My Trinity error log says " Incorrect Ledger device or changed mnemonic".

@FlensGold This would suggest that you are trying to access the wallet with a different Ledger, or your Ledger recovery phrase has changed.

**Comment by AntLopRod** [comment] 2019-06-16 17:40
1. Trinity version: 
0.5.2 and then 0.6.0
2. Ledger device IOTA app version (IOTA>About>Version):
IOTA 0.4.1
3. OS and version: 
Windows 7
4. Cannot add Ledger account even after wallet reset (Settings>Advanced Settings>Reset wallet) (y/n): Yes I can
5. Ledger uses an Index that is not 0 (y/n): 
Yes
6. Can you successfully add a non-Ledger account (y/n): 
Yes
7. You can get pass *Choose your Ledger account index* view successfully and pick an account name: (y/n): 
Yes
8. What error is appearing on the loading screen:
The balance that appears in the account is zero when it should be 447.05 Miotas
9. What happens after the error appears:
The account remains with zero balance
10. Is Ledger generating addresses on the Loading screen (*Generating Addr...* message appears several times on your Ledger device before the error appears) (y/n):
No

**Comment by steffenroeber** [comment] 2019-06-22 20:49
After a while working with 0.62 now I get again the node error:
Following log:
![trinity](https://user-images.githubusercontent.com/46009216/59968788-c14c6b80-953f-11e9-9166-4c250578d232.png)
Same ledger, same ledger app. After reseting the wallet all is fine again. Using the 'old backuped' trinity folder in appdata gives same error again.

**Comment by steffenroeber** [comment] 2019-06-22 20:55
After trying to restore wallet from Legder I got another error: Cannot connected to ledger. So I restarted the app on ledger and restoring finished successfully. but now my old backuped version from appdata also works. It seems that might be a bug in the connection with the ledger app/hardware.

**Comment by bsonnek** [comment] 2019-06-28 17:03
I had this same issue - I noticed If I closed the Ledger Live App and only had Trinity open, the issue resolved itself.

**Comment by cvarley100** [comment] 2019-07-08 12:36
As there are many different issues conflated into a single issue here I am going to close this one. 

If you are experiencing any issues with Ledger try the following steps

1. Follow this guide https://trinity.iota.org/help/ledger/
2. If this doesn't help, make sure you have your Ledger account index saved (find it on Account Management > View Seed) and your non-Ledger accounts backed up, and reset your Trinity wallet

Please do open a new issue if the problem persists, giving full details.

**Closed as completed by cvarley100** 2019-07-08 12:36 UTC
Labels: T - Bug, C - Desktop, P1 - Critical
