### ISSUE TITLE
Crash when importing seedvault

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#520] opened 2018-10-21 19:11 UTC
### Bug description
Trinity app crashes after selecting seedVault file to import and hitting ok.

### Environment Specs

- Manufacturer: Samsung
- Model: Galaxy s8+
- OS version: Android 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.5.1 (27) (Mobile)

### Steps To Reproduce
1. Create seedVault file and save to downloads
2. Select seedVault file for import and hit ok.
3. Experience a crash

### Expected behavior
The app should not crash and ask for a password to decrypt the seedVault file.

### Actual behavior
App Crashes

**Comment by rajivshah3** [comment] 2018-10-22 02:17
Duplicate of #517

**Closed as completed by rajivshah3** 2018-10-22 02:17 UTC

**Comment by jfghkl** [comment] 2018-10-22 10:13
Samsung Galaxy S7 Android 8.0 - the same.
